# Generated by Django 4.2.16 on 2024-09-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='usermanagement',
            name='user',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='UserManagement',
        ),
    ]
