# Generated by Django 4.2.16 on 2024-09-23 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0008_remove_department_name_department_departments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='department',
            new_name='departments',
        ),
    ]
