# Generated by Django 4.2.16 on 2024-09-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0009_rename_department_doctor_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='departments',
            field=models.CharField(blank=True, choices=[('Emergency', 'Emergency'), ('Pediatrics', 'Pediatrics'), ('Oncology', 'Oncology'), ('Radiology', 'Radiology')], max_length=30, null=True),
        ),
    ]
