# Generated by Django 4.2.16 on 2024-09-23 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0012_remove_patient_user_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 23, 20, 20, 44, 835959, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
