# Generated by Django 4.2.16 on 2024-09-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0019_doctor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='departments',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='departments',
            new_name='department',
        ),
    ]
