# Generated by Django 4.2.16 on 2024-09-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0027_prescription_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='billing',
        ),
        migrations.AddField(
            model_name='prescription',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
