# Generated by Django 4.2.16 on 2024-09-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0028_remove_prescription_billing_prescription_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
