# Generated by Django 4.2.16 on 2024-09-29 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0029_alter_patient_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medical_history',
        ),
    ]
